### ISSUE TITLE
Ignore Xcodefiles then use generated one

### ISSUE THREAD

**Issue by muizidn** [duckduckgo/iOS#1156]
Xcodeproj and Xcworkspace files should be ignored to avoid difficult conflict resolution. These conflict can be moving files, rename files, add files, remove files, modularization, and so on.
The solution is to use spec to generate these files. I personally use Xcodegen in my project for simplicity and Bazel for complex one.

Can I contribute to this project to implement above issue? I propose to use Xcodegen first because it is easier and inexperienced one with the tool can get grasp fast.

**Comment by samsymons** [comment]
Hey @muizidn,

Thanks for submitting this issue! Coincidentally, we chatted about this as a team recently, specifically discussing XcodeGen and [Tuist](https://tuist.io) as possible options. We decided that this isn't something we want to prioritize at this moment, but plan to trial XcodeGen using an internal project that's easier to migrate some time later this year.

We're a small team and rarely run into issues with Xcode project file conflicts thanks to our size, which is why this isn't a priority for us right now, but on the flip side that also means that we unfortunately don't have bandwidth to take on a contribution like this right now.
