### ISSUE TITLE
TrackerRadarKit crash when deserialising JSON

### ISSUE THREAD

**Issue by miasma13** [duckduckgo/iOS#1200]
**Task/Issue URL:** https://app.asana.com/0/414709148257752/1202407381883565/f

On older devices the JSON deserialisation when initialising TrackerRadarKit objects. Reason of the crash is that this code is done in scene initialisation and with slower performance the device is not doing it under assigned time and the app is killed by watchdog.
The source of the crash is **ContentBlockerRulesManager** initialisation (triggering JSON load) at scene creation time triggered from **MainViewController's** method: **prepare(for:sender:)**

**Proposal**
One of the approaches at fixing this one of high ranking crashes would be to: 
- identify code paths triggering the ContentBlockerRulesManager initialisation from MainViewController's method: prepare(for:sender:)
- decouple the initialisation from the scene loading

**Comment by bwaresiak** [comment]
Are we sure this is the only place where the problem lies? There are more places in the iOS scene initialization flow that reach to TDS, like fallback in `DefaultContentBlockerUserScriptConfig:54` or `DefaultSurrogatesUserScriptConfig:60` to load `trackerDataManager?.trackerData` in case nothing is provided - and it is invoked by `viewDidLoad` logic on Tab initialization:

<img width="430" alt="init_flow" src="https://user-images.githubusercontent.com/2865434/174300590-836a54a6-8e96-48cf-a4ea-7d0370bab326.png">

As it is called in `MainViewController.viewDidLoad()` flow, could that also cause above issue?

**Comment by mallexxx** [comment]
@bwaresiak valid concern, what do you think about refactoring the CBR/UserScripts loading to Publishers sequence and waiting for CBRs to finish compiling in decidePolicyForNavigationAction?

**Comment by bwaresiak** [comment]
Yes - but we need to wait for @jaceklyp's code to land (days I guess?) as he is working on first loading improvements.

**Comment by mallexxx** [comment]
I made an initial effort refactoring the ContentBlockingRules to async waiting and loading as a single asset;
@bwaresiak when you have time please check and we‘ll have a chat to validate the approach

**Comment by samsymons** [comment]
@mallexxx Closing this out as the original PRs have been merged, and the Asana task is complete. Of course, feel free to re-open if there's more work to do that I'm not aware of.
