### ISSUE TITLE
WebRTC leakage on iOS and iPadOS 16 

### ISSUE THREAD

**Issue by W6C** [duckduckgo/iOS#1249]
Device OS: iOS 16 & iPadOS 16
DuckDuckGo version:7.68.6.0
Problem:
1, webrtc leaks real ip over VPN on both iPhone and iPad.
2, clicking email protection causes immediate crash on iPad.

**Comment by samsymons** [comment]
Hey @W6C! Thanks for submitting this – the second issue should now be fixed in the latest release.

I'll file the first issue with the team and get back to you.

**Comment by rokas-ambrazevicius** [comment]
1. As far as I remember, Apple has an issue in their Network framework.
This is an ongoing Apple bug for quite a while now.  I had a chance to debug the flow, and I filed a bug report back in 2021. 

In short, after connecting to VPN, a VPN tunnel appears. After connection, there are 2 tunnels, one routing traffic through VPN, one not routing anything. Due to WebRTC nature of trying to find a peer connection, WebRTC manages to leak through the tunnel, which is not connected to a VPN.
