### ISSUE TITLE
Bottom Bar

### ISSUE THREAD

**Issue by WillHick** [duckduckgo/iOS#1372]
When will a bottom bar option be available, the one reason from me migrating to the DDG browser?

**Comment by samsymons** [comment]
@WillHick Thanks for suggesting this! This is a pretty popular request, and one that has come up again internally earlier this month. I can't promise any real timeline, but it's something we're looking into.

Since this is tracked internally, I'll close this issue down, but will ping you here once there's something to report.

Thanks again!

**Comment by WillHick** [comment]
Are we any closer to this feature?
