### ISSUE TITLE
[Error] Install fonts - Build step

### ISSUE THREAD

**Issue by timpalade** [duckduckgo/iOS#261]
I got an error from this script, when building, saying that it cannot find anything at `~/DuckDuckGo/Fonts/proximanova/`. This path seems to be a Bundle path (visible inside the Xcode project), but it is not there on disk. 

That aside, it tries to copy the fonts in this folder `$SRCROOT/fonts/licensed`. But the fonts are already there. 

I don't know why you guys have this step, but to me, it seems unnecessary.

**Comment by brindy** [comment]
The fonts in that folder are fake placeholders. 

Proxima Nova fonts are commercially licensed so us devs at DDG have copies on our computer because we're licensed to. As such the build tries to copy in the licensed fonts from an external location.

See the readme linked under the "Fonts" heading on the main readme.

**Comment by timpalade** [comment]
@brindy Thanks for the fast reply. For someone outside of DDG, this does not seem like a necessary step to build the project. On the simulator, the app seems to work just fine, with the dummy fonts. Maybe I am missing something. 

So to make the setup process smoother maybe something can be done about this. Maybe a flag?

**Comment by brindy** [comment]
@timpalade - I'm inclined to agree. Should be able to checkout the code, build and run it in more or less a one-liner, assuming a dev environment is set up as standard, which seems valid given this is Xcode. :)

If you can improve this via PR, I'd be happy to look at it, otherwise it's definitely on my list to look at later (we're responding to feedback from the launch just now).

**Comment by timpalade** [comment]
@brindy Sure, it is not critical, but it would be nice. I will think about a solution. 
On a different note, I think you guys did a pretty good job!

**Comment by brindy** [comment]
Thanks @timpalade - much appreciated! :D

**Comment by timpalade** [comment]
@brindy I think I found a solution. I modified the script to check if `~/DuckDuckGo/Fonts/proximanova/` exists. If it does not exist, it does not copy the fonts. What is the probability that someone outside of DDG will have this directory? I would argue it is close to 0, if not 0. 

I made a pull request with it.

**Comment by brindy** [comment]
Hit the close button by mistake sorry. :) 

We're just finishing up a couple of other improvements and then will get on to community provided PRs. Thanks for your patience. :)

**Comment by brindy** [comment]
Fixed in #262 - thanks for the contribution @timpalade :)
