### ISSUE TITLE
iPhone 5 support

### ISSUE THREAD

**Issue by mfpierre** [duckduckgo/iOS#293]
Hey,

It seems since https://github.com/duckduckgo/iOS/commit/13a22ac4d7f47df1a966d187291744bbddcae559 I can't update to `7.2.0` on my iPhone 5 through the App Store. (the target is iOS 10 but the iPhone 5 (which can run iOS 10.3.3) is 32bits)

It's not stated in the changelog, was this intentional?

I'm stuck with an upgrade I can't to in the app store, it's a bit annoying 😑

**Comment by brindy** [comment]
Sorry for the delay in response.  

This change was intentional, but we forgot to add it to the change log, sorry about that.

We dropped support for both iOS 9 and 32bit due to performance of the privacy solution, but we've made some improvements recently and are constantly re-evalulating.

Thanks for taking the time to give us feedback!

**Comment by janicetyler** [comment]
Good Idea's This change was intentional, but we forgot to add it to the change log, sorry about that.
We dropped support for both iOS 10 and 64bit due to performance of the privacy solution, but we've made some improvements recently and are constantly re-evalulating.
[https://github.com/janicetyler](https://github.com/janicetyler)
[https://github.com/janicetyler/wood-kitchen-cabinets](https://github.com/janicetyler/wood-kitchen-cabinets)
[https://janicetyler.github.io/wood-kitchen-cabinets](https://janicetyler.github.io/wood-kitchen-cabinets/)

**Comment by lucialam172** [comment]
This change was intentional, but we forgot to add it to the change log, sorry about that.
We dropped support like this 
[https://github.com/lucialam172/dark-kitchen-cabinets](https://github.com/lucialam172/dark-kitchen-cabinets)
[https://github.com/lucialam172](https://github.com/lucialam172)
[https://lucialam172.github.io/dark-kitchen-cabinets](https://lucialam172.github.io/dark-kitchen-cabinets)
