### ISSUE TITLE
DDG 180 Degree Text Flip in Search Result

### ISSUE THREAD

**Issue by mattlikespie** [duckduckgo/iOS#3013]
In all instances of DDG I use (DDG for iOS, DDG macOS) and all browsers using DDG Search (Tor, Safari, Firefox on iOS or macOS), when I type the search terms below, the result preview / confirmation appears flipped 180 degrees.

rotate text box in windows preview with mouse 20degrees

Also happens for:

rotate text box in mac preview with mouse 20degrees

https://github.com/duckduckgo/iOS/assets/113533724/cc1f7172-4989-4e19-b668-c7443d471ef1

**Comment by brindy** [comment]
Hello, thanks for your feedback.  This is deliberate and not specific to our apps. 😄 

This is what's known as an "instant answer" and we've been doing this for many years. We have many of them that will trigger depending on the words you use in your search.

Try some of the following:

`user agent`
`qrcode hello world`
`roll d20`

We also have ones that are a bit more involved: 

`weather in London`
`coffee shops in Paris`

So that's what is happening and shouldn't affect the search result you get.

Hope that helps.

Thanks!
