### ISSUE TITLE
Ideal payment (dutch) not supported

### ISSUE THREAD

**Issue by siemvaessen** [duckduckgo/iOS#325]
It is currently impossible for DDG to handle payments via the Ideal platform. Any support coming for this? 

Error states: unsupported url

**Comment by brindy** [comment]
Hello,

Is it https://www.ideal.nl/en/ ?

If not, can you provide supporting URLs, please?

Thanks!

**Comment by siemvaessen** [comment]
Hi,

I will try and provide documentation / logs this week. 

Thanks, Siem

**Comment by siemvaessen** [comment]
Ok, here is what happens. User chooses Ideal as form of payment provided by shop (https://www.ideal.nl/en/) - you choose a bank, Triodos bank for example and the following link is generated:

https://ideal.triodos.nl/ideal-online/pages/mobile-switch.actiontrxid=LOTSOFNUMBERSHERE&cc=LOTSOFNUMBERSHERE - which is session cookie based, but is already pointing to Triodos. 

Once clicked user gets sent here:

triodosmobilebanking://target=ideal/txid=0050003316460519/securecode=1711016533220177

Which seems like an internal/local reference and that is where DDG iOS provides the error message unsupported URL which I gues is the "triodosmobilebanking://target" part.

I tried other banks as part of the iDeal options, but the others have the same errors.

Hope this helps. If not, let me know.

**Comment by brindy** [comment]
Thanks @siemvaessen 

That confirms what I was thinking.  The `triodosmobilebanking://` is a custom URL scheme. Our app only supports a handful of these at the moment (e.g. sms://, tel://, mailto:// etc).

We don't support all of them because they're not very secure.  Any app could say it handled `triodosmobilebanking://`

However, the are situations (like OAuth) where this should probably work. I've raised it with the team and we are discussing how to proceed.  (I'm suggesting some kind of prompt and whitelist/blacklist approach)

Thanks for raising it with us!

**Comment by siemvaessen** [comment]
Makes sense. However, I am a big DDG fan (early stages, years ago) but I still need to switch to Safari iOS in order to pay. Anyway, support for this would be great.

**Comment by brindy** [comment]
Thanks for your long support! It's appreciated.

Am going to close this off from here as we have it tracked internally. 

Thanks again.
