### ISSUE TITLE
Xcode 16 runtime crash

### ISSUE THREAD

**Issue by iccub** [duckduckgo/iOS#3300]
Once compilation errors are fixed for Xcode 16, any website you visit causes a runtime crash.
The crash seems to come from GRDB library, from the example in the screenshot even if you disable the top method `neverPromptWebsites` it is going to crash in another places where a db call is made.
I did not dig into more details yet.

STR
1. Run the app on Xcode 16
2. Open example.com website

Happens on sim and real device.

<img width="1241" alt="Zrzut ekranu 2024-08-31 o 16 05 49" src="https://github.com/user-attachments/assets/616b8975-5a1c-4102-b3b5-1ea32081bbf2">

**Comment by iccub** [comment]
Seems to be tracked by the GRDB maintainer https://github.com/groue/GRDB.swift/issues/1596 closing for now

**Comment by groue** [comment]
There was a new report of this crash with the latest Xcode 16 RC: https://github.com/groue/GRDB.swift/issues/1619

I strongly suggest filing feedbacks on http://feedbackassistant.apple.com/, and/or at http://github.com/swiftlang/swift/issues/, because it does not look like anything can be done at the level of GRDB. I mean: _a Swift existential crashes at runtime_, this is a pretty big compiler bug.

**Comment by iccub** [comment]
I'll reopen it thanks(feel free to close it ddg team). I have not checked on latest Xcode yet

**Comment by iccub** [comment]
Xcode 16 RC 16A242 does not crash for me on local build on simulator
