### ISSUE TITLE
Yubikey support?

### ISSUE THREAD

**Issue by jplock** [duckduckgo/iOS#476]
Any thoughts on integrating https://github.com/Yubico/yubikit-ios to support Yubikeys similar to what Brave did at https://github.com/brave/brave-ios/pull/1158?

**Comment by brindy** [comment]
Looks interesting, thanks for the heads up.  Think I'll buy myself a YubiKey to play around with. :)

**Comment by samsymons** [comment]
Hey @jplock! We're gonna sit tight on this one for now, since full WebAuthn support is on the [WebKit roadmap for this year](https://trac.webkit.org/wiki/AppleWebKitGoalsfor2021):

> Parity goals include WebAuthn for all WKWebViews

Thanks for the suggestion. I'd love to have YubiKey support too, so here's hoping that WWDC brings us some good news. 🙂
