### ISSUE TITLE
!Bang deep links

### ISSUE THREAD

**Issue by AustinConlon** [duckduckgo/iOS#522]
I’d like to be able to go straight into the relevant app when doing a !Bang search. For example, !q should take the user straight into the Quora app rather than display the mobile site.

**Comment by brindy** [comment]
Thanks for the suggestion, and sorry for not replying sooner.  

There's a few problems with this:

1) When you use a bang you go directly to the site, because you didn't explicitly click a link it doesn't open the app using the [universal link](https://developer.apple.com/ios/universal-links/).   You maybe be better off searching for your subject and adding 'quora', or whatever site, to your search query. If you have the app installed then hopefully it will launch the right app for you when you tap the link on the search results page.

2) If we wanted to support bangs opening other apps then we'd have to check for the existence of the target app, but the target app would also need to support a url scheme.  This is because we can't trigger universal links automatically, so we'd have to work out what all the possible url schemes for all possible apps are.  Apart from being an arduous task, even if it is possible, iOS limits the number of url schemes you can query for so, wouldn't we be able to support a lot of apps and that wouldn't be hugely useful or fair to apps that we don't support.

3) Related to the above, url schemes are not guaranteed to be associated to one app.  Any app can support any url scheme so we couldn't even be sure that we're opening the app you desire and that could be a privacy / security issue.

As such, I'm going to close this out as it's we're unlikely to do anything in this area, but your feedback has been noted.  Sorry we couldn't be more helpful here and thanks for your continued use of our app!

**Comment by AustinConlon** [comment]
No worries, and thank you for the detailed explanation!
