### ISSUE TITLE
Add a Safari Content Blocker

### ISSUE THREAD

**Issue by macmanx2** [duckduckgo/iOS#524]
Like your newly relaunched macOS app, please consider extending this app’s tracker blocking as a Safari content blocker, similar to Firefox Focus. 

Bonus points if it includes an allow list, which Firefox Focus doesn’t have. ;)

**Comment by tankmohit** [comment]
Yes, Please.

**Comment by bwaresiak** [comment]
Hello,

Thank you for your feedback - I've passed this to the Product team.

Thanks!

**Comment by macmanx2** [comment]
Thanks! :)

**Comment by brindy** [comment]
Sorry for the delay here, we kept putting it off and then iOS 14 default browser happened so we were waiting to see where the land lay after all that.

So the two main things here are:

1) A content blocker extension (CBE) will break a lot of sites because it will need to block Google Tag Manager and other such scripts for it to be an effective tracker blocker.  However, the CBE doesn't allow us to replace those scripts with dummy code that does nothing. 

2) Now that we are available as a default browser (as are many other browsers) there's much less chance of being launched into Safari (though you will still get Safari View Controller usage, yes). 

As such, we are unlikely to expose our tracker blocker via Content Blocker Extension any time soon, I'm afraid.  However, please be assured that is is something we review internally fairly often so if the situation changes will also adapt our stance.

Thanks!

**Comment by rhwood** [comment]
Please re-review this decision not to provide this.

I use the DuckDuckGo Safari Extension in macOS with great effect, and find that the Firefox Focus content blocker on iOS blocks too much. The DuckDuckGo Safari Extension in macOS does not block content that Firefox Focus does. I rely on features of the Safari browser and other apps that support extensions in it too much to be able to switch to another browser app for the purposes of using DuckDuckGo as opposed to other privacy services.

(I have other extensions running that do transform (not just block) content, so I'm certain it is possible to make at least some transformations work.)
