### ISSUE TITLE
Retain cycle in EasyTipView extension

### ISSUE THREAD

**Issue by Johennes** [duckduckgo/iOS#621]
Noticed this when investigating #617. Reproduction steps on `master` (`53c29feb96f1dbb52c94112d0a9be9aebf33bc92`):

- Fresh install the app
- Click through the onboarding
- Perform two navigations, e.g. open stackoverflow.com, then twitter.com (by now 3 tips should have shown)
- Fire up the memory graph debugger and notice that 3 instances of `TouchView` are stuck in memory

One of them showed a `NotificationCenter`-related cycle for me.

![Screenshot 2020-04-10 at 21 10 49](https://user-images.githubusercontent.com/1137962/79018243-9fc27c00-7b73-11ea-99fd-e706803c1f91.png)

The code in question is this

```
func handleGlobalTouch(completion: @escaping () -> Void) {
    
    let view = TouchView()
    UIApplication.shared.keyWindow?.addSubview(view)
    
    var token: NSObjectProtocol?
    token = NotificationCenter.default.addObserver(forName: TouchView.touchNotification, object: nil, queue: nil) { _ in
        view.removeFromSuperview()
        self.dismiss()
        completion()
        NotificationCenter.default.removeObserver(token!)
    }
}
```

I am not entirely sure how this creates a strong reference cycle. My suspicion is that `NotificationCenter` creates a strong reference between the poster (`view`) and the block. With the block strongly capturing the view, that would then create the cycle back to itself. Using ` [unowned view]` inside the block seems to break the cycle.

I think this issue should be low impact because you only seem to show a limited number of tips during the first few actions inside the app so the amount of leaked memory is constant.

**Comment by bwaresiak** [comment]
Hello, @Johennes 

Thanks for bringing tis up! This is pretty interesting problem.

In theory 😄, this should not create strong reference cycle: both `self` and `view` are held strongly by the block, but the block is outside of the view hierarchy and seem to be only referenced by NotificationCenter.

But as you described, we still get a leak. Moreover, when I tested adding capture list `[weak view, weak self]` it didn't solve the problem completely (some things were still leaking).

But.. there is one additional thing that is captured: token. Token is described as:
```
(lldb) po token
▿ Optional<NSObject>
  - some : <__NSObserver: 0x600002c449c0>
```

and when [we dig deeper](https://github.com/nst/iOS-Runtime-Headers/blob/master/Frameworks/Foundation.framework/__NSObserver.h) it turns out this can hold reference to the block. So, here is our cycle.

Now, we cannot really make token weak, as it is not held by anything outside of that block and deallocates instantly, but we can check if clearing token reference breaks the cycle:
```
        var token: NSObjectProtocol?
        token = NotificationCenter.default.addObserver(forName: TouchView.touchNotification, object: nil, queue: nil) { _ in
            view.removeFromSuperview()
            self.dismiss()
            completion()
            NotificationCenter.default.removeObserver(token!)
            token = nil //break reference cycle
        }
        tokenWrapper.add(token)
```
With this code, everything works for me as expected.

Once again, thanks for bringing this interesting problem up. :)

**Comment by Johennes** [comment]
Holy cow! This is mind-boggling. I missed that even with `view` being weakified, there were other things leaking that related to this. Never would have thought the token to be the culprit given that Apple uses the exact same code in the [docs](https://developer.apple.com/documentation/foundation/notificationcenter/1411723-addobserver). 🤦‍♂️
