### ISSUE TITLE
Custom URL schema not working for https://lichess.org/

### ISSUE THREAD

**Issue by MathPlayer** [duckduckgo/iOS#661]
The most known open-source chess platform, https://lichess.org/ has the custom URL schema implemented in order to open certain links in the iOS app (if installed). This flow does not work with the DuckDuckGo iOS app.

How to reproduce:
Open the https://lichess.org/ link in DuckDuckGo from another app.
The easiest way for me was to write a message to myself on the Facebook Messenger app, long tap the link and choose "Open in DuckDuckGo".

Expected outcome:
The lichess iOS app is opened.

Actual outcome:
The browser either crashes (already did 2 or 3 times) or it loads the page in the browser without following the custom URL schema.

Without any browser installed, if I do the same flow using Safari, the iOS app is opened.

I mentioned it as well as a [comment](https://github.com/duckduckgo/iOS/pull/644#issuecomment-648661532) on #644 .

Tools and versions:
- iPhone 11 PRO with iOS 13.5.1.
- DuckDuckGo version 7.47.0.0 (latest coming from the App Store) with default settings (e.g. "Open Links in their Associated Apps" is on).

**Comment by brindy** [comment]
Hi,

Thanks for getting in touch. 

Firstly, this is about [universal links](https://developer.apple.com/ios/universal-links/), not custom URL schemes.  I just want to get that clarification in because URL schemes are a different issue and we handle them differently.

The reason this is happening is because we handle the incoming URL and tell WKWebView to open it, which seems reasonable to us since we've just been told to open that URL.  However, the problem is that if you tell WKWebView to open a URL explicitly, even if there's an associated app, WKWebView will load and show the page. 

(Note that if WKWebView see that a user has navigated from a page to a URL for which an associated app is installed then it will open the associated app, but not if already browsing that domain)

Unfortunately there's no way for us to know that the lichess app is installed otherwise we could just tell the system to open the URL.

In the short term - don't open lichess links in our app if you want them to launch the lichess app directly.  There should be no loss of privacy here because the operating system will just do that directly.

In the medium/longer term we plan to support being default browser for iOS 14 - at this point you can just click on all links to open our app and the system will automatically open associated apps as expected.

The crash is a separate issue and we'll look in to that.

Hope that makes sense.

Thanks,
Brindy

**Comment by MathPlayer** [comment]
I'm sorry for the mislead. For some reason, I was expecting the service itself (e.g. the lichess server) to determine that you're on iOS and/or you have the app installed, so redirect the request to a custom URL schema like `lichess://something`, but that's obviously not possible.
I can only wait for iOS 14 and its changes.

**Comment by brindy** [comment]
No problem! We're excited about iOS 14 too. :)

Thanks again for getting in touch.
