### ISSUE TITLE
Allow clearing of DuckDuckGo.com cookies

### ISSUE THREAD

**Issue by a60wattfish** [duckduckgo/iOS#670]
It’s currently hardcoded in Core/WebCacheManager.swift to not clear cookies for duckduckgo.com when data is deleted and there are no options anywhere for clearing it.

I can understand the reasons why it’s hardcoded, however my suggestion would be to make DuckDuckGo.com a toggleable option under the “Fireproof Websites” menu.

Another menu could be added for setting search settings if cookies aren’t stored, which can then easily be passed using URL parameters.

**Comment by nilnilnil** [comment]
Hey a60wattfish, thanks for making this. We really appreciate the feedback, since we’re always looking for ways to to better align with our product vision of "Privacy, simplified." Just to be clear for anyone looking at this thread, both our apps and our search engine are fully anonymous as enforced by our strict privacy policy (DuckDuckGo.com/privacy). As that policy explains in more detail (and as you correctly pointed out), these cookies are non-personalized settings on the search engine that are user-set from our settings pages and dialogs, and as such are expected to be persistent. Since we don't have accounts (unlike other search engines), they need to be stored somewhere on device (which is in any case more private). Nevertheless, we’re going to spend some time thinking through an alternative means to give folks the same level of privacy in a simpler way that is more transparent. Stay tuned. We'll keep this open for now and report back after we have a more concrete plan.

**Comment by catehstn** [comment]
The DuckDuckGo application is a search and browse application, and the SERP page is a central feature of the application, and both the SERP and the application adhere to our privacy policy(https://duckduckgo.com/privacy) and do not collect or share any personal information.

After going through user feedback and the code, we concluded that:

- The average user does not distinguish between the app and the search page. On occasions bugs cause DuckDuckGo cookies not to be persisted after pressing the fire button, we see significant user confusion though feedback. 
- Exploring options such as using URL parameters had a higher failure rate than persisting the cookies and interacted poorly with the back button.
- We could better document this special treatment of DuckDuckGo cookies in the code for clarity and transparency.

As a result, we've made some changes to the code in #705 and  [Android#930](https://github.com/duckduckgo/Android/pull/930) to make it clearer what is happening here. These cookies contain purely settings (such as default language, theme), and are not stored in a personally identifiable way.

Thanks again for raising this concern.
