### ISSUE TITLE
Ensure text is selected when focussing the address bar.

### ISSUE THREAD

**Issue by brindy** [duckduckgo/iOS#741]
**Steps**

* Load a web page
* Tap the address bar

**Expected**

* The text is selected so that it can be copied/replaced easily

**Actual**

* Sometimes the text is not selected properly

**Comment by lm2s** [comment]
Hello, hope you don't mind, I've taken the liberty of submitting a PR for this issue.

From what I could gather the issue seems to come from the cursor being set when `becomeFirstResponder()` is called and interfering with the call to `selectAll(nil)`.

I also considered replacing the `self.textField.selectAll(nil)` with `self.textField.selectedTextRange = self.textField.textRange(from: self.textField.beginningOfDocument, to: self.textField.endOfDocument)` to keep the beginning of the address visible when selecting long urls instead of scrolling to the end. But since it's a change in behavior I refrained myself before discussing it here.

**Comment by brindy** [comment]
Thanks @lm2s - going to review it just now.

**Comment by brindy** [comment]
What you've done works me.  Thanks!
