### ISSUE TITLE
Add a back and forward stack with current tab's history

### ISSUE THREAD

**Issue by moyerr** [duckduckgo/iOS#764]
Most modern browsers (mobile and desktop) allow you to inspect your current tab's history by pressing and holding either the back or forward buttons. This is a feature I miss dearly when I use the DuckDuckGo Browser, and would love to see it added to the app!

I have [implemented the feature on my fork](https://github.com/moyerr/iOS/tree/feature/back-forward-navigation) if you would like to take a look at one possible solution. It is adaptive to size classes and app theme, and the behavior and user interface mimic how Safari handles this feature. 

I have attached screen recordings below to see how it works on different devices and OS versions.

## iPad

iPadOS 14 (side-by-side with Safari): 
![iPadOS 14](https://thumbs.gfycat.com/SpitefulFaithfulDanishswedishfarmdog-size_restricted.gif)

iPadOS 13.5 (side-by-side with Safari): 
![iPadOS 13.5](https://thumbs.gfycat.com/ArtisticAdmiredLaughingthrush-size_restricted.gif)

## iPhone

iOS 14: 
![iOS 14](https://thumbs.gfycat.com/RegalBigheartedGuillemot-size_restricted.gif)

iOS 13.5: 
![iPad 13.5](https://thumbs.gfycat.com/MeagerEdibleIndusriverdolphin-size_restricted.gif)

**Comment by brindy** [comment]
Hi Robbie,

Thanks for the suggestion. I like this and the UX looks good, but I would have to run it past our internal product review team first to see if they want to proceed with it.  Let me do that and get back to you (might be a week or two because I'm on leave next week).

One quick question though - which iPad was this on?  Reason I ask is that I noticed when in Side by Side mode with Safari you're seeing the toolbar at the bottom, but you  should be getting the new tabs view in that mode.  You should only see the "iPhone" view in the slimmest of views so that looks like a bug to me and I'd like to investigate that.

Thanks,
Chris

________________________________

**Comment by moyerr** [comment]
@brindy Thanks for the update! I'll do my best to keep my branch up to date with `develop` in the meantime.

To answer your question, that was the iPad Pro (11-inch, 2nd generation) in both screen recordings.

**Comment by brindy** [comment]
Hi @moyerr 

Sorry for the delay here, I took some leave and we didn't manage to progress this internally.  Is it something you are still interested in doing?  If so I can push it internally this week.

Thanks!

**Comment by moyerr** [comment]
@brindy No worries at all, I hope you enjoyed your time away! 

Yes, I have a full implementation on my fork at https://github.com/moyerr/iOS/tree/feature/back-forward-navigation, and have been keeping it up to date with the latest on `develop` here. Would love to see this feature adopted in some capacity, even if it doesn't look exactly like my implementation. But say the word, and I'd be glad to open a PR!

**Comment by brindy** [comment]
Hello, I ran it past the team and we decided that we'd like to bring the design in house so that we can get the UI/UX just right.   What you've done is great, but we'd like to do something closer to what Safari has with a custom component that possibly works on iOS 13 as well.  Thanks again for your suggestion and for your interest in DuckDuckGo!

**Comment by moyerr** [comment]
Thanks for the update @brindy! I look forward to seeing this feature come to the app in the future!

**Comment by lucialam172** [comment]
It has been released now, correct? So, this should be updated to 
[https://github.com/lucialam172/dark-kitchen-cabinets](https://github.com/lucialam172/dark-kitchen-cabinets)
[https://github.com/lucialam172](https://github.com/lucialam172)
[https://lucialam172.github.io/dark-kitchen-cabinets](https://lucialam172.github.io/dark-kitchen-cabinets)
