### ISSUE TITLE
Where can I download old repo like duckduckgo/Kingfisher?

### ISSUE THREAD

**Issue by kainjinez** [duckduckgo/iOS#822]
I've forked DDG long time ago. At that time I was able to build DDG with Carthage.
But now I can't, Cartfile did not found any repo below. How can I get it to let it work?
I don't want to pull newest right now, because I modified a lot. Thanks.

```github "duckduckgo/Kingfisher" ~> 4.10.0

github "duckduckgo/Device.swift" ~> 1.1.2

github "duckduckgo/Toast-Swift" ~> 4.0.0

github "duckduckgo/Alamofire" ~>  4.8.1

github "duckduckgo/OHHTTPStubs" ~> 7.0.0

github "duckduckgo/CommonCrypto" ~> 1.1.0

github "duckduckgo/SimulatorStatusMagic" "tags/1.9.5"

github "duckduckgo/swifter" == 1.4.3

github "duckduckgo/lottie-ios" "tags/2.5.0"

github "duckduckgo/PunycodeSwift" "master"

github "duckduckgo/EasyTipView" "brindy/icon_support"
```

**Comment by samsymons** [comment]
Hey there @kainjinez,

We migrated the DuckDuckGo iOS app to use Swift Package Manager last year, and as a result the forks used by older versions of the app were removed. There are two paths forward that I can see, given that you’re unable to sync your fork with `develop`:

1. Update each dependency in your Cartfile to point to the original repo instead of the DuckDuckGo fork, e.g. update `github "duckduckgo/Alamofire" ~>  4.8.1` to point to `github "Alamofire/Alamofire" ~>  4.8.1`. This may result in some build failures in cases where we had previously modified our forks, but I expect this to be minimal as the current version of the iOS repo is using Swift packages directly with no modifications.
2. If you still have the Carthage build artifacts cached locally, it should contain the last successful checkouts; look under `Carthage/Checkouts` and see if the original source files are all there. If they are, you could push them to new forks under your own GitHub account and update the Cartfile to use them.

That's about all the help we can offer – sorry for the trouble, and thanks for filing an issue!
