### ISSUE TITLE
Can't download .mobileconfig

### ISSUE THREAD

**Issue by iGlitch** [duckduckgo/iOS#830]
Trying to download any .mobileconfig from https://encrypted-dns.party/ for example opens it as a readable file rather than a profile that can be installed.

Is it a limitation for being a third party browser/something only Safari can do? 
or is it a bug?

**Comment by brindy** [comment]
Hi! Thanks for reaching out. 

Yes, this is a known issue sadly, but we're working on a fix.  It's partly due to there basically not being good download APIs in WKWebView but there are work arounds (which we haven't felt needed to be prioritised until recently, ie default browser), and Apple are rolling out new APIs in future versions of iOS 14.  So it will definitely be fixed "soon" - hopefully before iOS 15 anyway! :) 

Hope that helps.

**Comment by Johennes** [comment]
Maybe a good temporary workaround could be to open `*.mobileconfig` URLs in `SFSafariController`? That'd be very little work and even includes the system messaging about how to actually install the profile.

![Simulator Screen Shot - iPod touch (7th generation) - 2021-04-11 at 21 25 23](https://user-images.githubusercontent.com/1137962/114318247-8fd5d300-9b0c-11eb-8229-dad6ae361936.png) ![Simulator Screen Shot - iPod touch (7th generation) - 2021-04-11 at 21 25 26](https://user-images.githubusercontent.com/1137962/114318248-8fd5d300-9b0c-11eb-8d94-4d44c9ff7ae1.png)

**Comment by brindy** [comment]
Hi, thanks for this.  We are tracking it internally here: https://app.asana.com/0/414709148257752/1199680686183984 and are hoping to schedule a general overhaul of the Downloads capability of this browser soon.  Thanks!
