### ISSUE TITLE
Contribute to the translation?

### ISSUE THREAD

**Issue by zefr0x** [duckduckgo/iOS#840]
Can I contribute to the translation? I want to add the Arabic language to the app.
I don't know, but i saw [this folder](https://github.com/duckduckgo/iOS/tree/develop/BookmarksTodayExtension). I didn't find any explanations in the README.

**Comment by serhatbadan** [comment]
I can add the Turkish language to the app.

**Comment by brindy** [comment]
Hi, thanks @ZER0-X and @serhatbadan for your kind offers, but we use an external translation company and have a process which requires certain files to be kept in sync.

@ZER0-X - Regarding Arabic, I'm very keen to add this, but we haven't done a great deal with RTL support yet.   While we couldn't accept the contribution we'd love to see a demo of this if there was a quick way to do it so that we could evaluate how much work there is to do to support Arabic.

@serhatbadan The app is already translated in Turkish.  If you are finding specific problems can you please create an issue and list the problematic text (with English translation if possible and what the actual translation should be).

Thanks!

**Comment by serhatbadan** [comment]
@brindy Thank you for your feedback. If i find specific problem in app, i'll create an issue. 
Greetings!
