### ISSUE TITLE
URL autocomplete recommends malicious sites

### ISSUE THREAD

**Issue by fruityperson** [duckduckgo/iOS#875]
When typing into the URL bar in DuckDuckGo iOS browser, it often suggests malicious sites (e.g. `web.archvie.org` instead of `web.archive.org` and `maps.goggle.com` instead of `maps.google.com`).

It would be very useful to hide those URLs from suggestions, especially on mobile where it's harder/slower to type the full URL and users don't pay much attention to small text. 
Also for a privacy/security-focused browser this is important. 

<img src="https://user-images.githubusercontent.com/75911466/117565496-ec97bf80-b0b1-11eb-92c5-f2ae111998ee.jpeg" width="200">
<img src="https://user-images.githubusercontent.com/75911466/117565500-eefa1980-b0b1-11eb-9119-03683416a9dd.jpeg" width="200">

**Comment by brindy** [comment]
Hi, thanks for this and sorry for the delay in replying.  

We are just rolling out a new version (7.63.5) which deals with this better.  The suggestions you've found should really have been search suggestions rather than URLs.   We now only treat a suggestion as a URL when the backend tells us to.

Going to close this out, but please do comment/re-open if you have any further problems.

Thanks.

**Comment by fruityperson** [comment]
Hi, thanks for your response. Looking forward to the release of new version! Will re-open the issue if it appears after the fix.
